/* eslint-disable @next/next/no-page-custom-font */
import type { AppProps } from 'next/app';
import { Roboto } from '@next/font/google';
import { lightTheme } from '@theme';
import { ThemeProvider } from '@mui/material';
import Head from 'next/head';
import './../styles/global.css';
import { LoginLayout } from '@components';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Saayam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto&display=swap"
          rel="stylesheet"
        />
        <style jsx global>{`
          html {
            font-family: ${roboto.style.fontFamily};
          }
        `}</style>
      </Head>
      <ThemeProvider theme={lightTheme}>
        <LoginLayout>
          <Component {...pageProps} />
        </LoginLayout>
      </ThemeProvider>
    </>
  );
}
